### ISSUE TITLE
freeCodeCamp - Building a Tribute Page

### ISSUE THREAD

**Issue by yzhbankov** [nesterone/sf-eng-init-fellow#46]
https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/02-browser/02-basic-html-css-jquery/basic-html-css-jquery.md#project-freecodecamp----building-a-tribute-page

**Comment by yzhbankov** [comment]
close #46
http://codepen.io/yzhbankov/pen/aZmOvg

**Comment by nesterone** [comment]
move all inline styles to CSS
