### ISSUE TITLE
freeCodeCamp - Build a Personal Portfolio Webpage

### ISSUE THREAD

**Issue by yzhbankov** [nesterone/sf-eng-init-fellow#47]
https://github.com/nesterone/sf-eng-init-gl-spring-2016/blob/master/02-browser/02-basic-html-css-jquery/basic-html-css-jquery.md#project-freecodecamp----build-a-personal-portfolio-webpage

**Comment by yzhbankov** [comment]
close #47
http://codepen.io/yzhbankov/pen/wWzedO?editors=1100

**Comment by yzhbankov** [comment]
close #47
http://codepen.io/yzhbankov/pen/wWzedO?editors=1100

**Comment by yzhbankov** [comment]
close #47
http://codepen.io/yzhbankov/pen/wWzedO?editors=1100

**Comment by nesterone** [comment]
move inline styles to CSS classes
